# Generated by Django 3.0.2 on 2020-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amzspy_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amzurl',
            field=models.CharField(max_length=500),
        ),
    ]
