# Generated by Django 3.0.2 on 2020-02-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amzspy_us', '0002_auto_20200221_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amzurl',
            field=models.URLField(max_length=500),
        ),
    ]
