# Generated by Django 3.0.2 on 2020-02-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amzspy_us', '0003_auto_20200221_0526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendurl', models.URLField(max_length=500)),
                ('sendemail', models.URLField(max_length=254)),
                ('sendprice', models.FloatField(max_length=50)),
            ],
        ),
    ]
