# Generated by Django 3.0.2 on 2020-02-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amzspy_us', '0004_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='sendemail',
            field=models.EmailField(max_length=254),
        ),
    ]
